### PR TITLE
Docs: add CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by a-developer-and-her-mac**
Adds CONTRIBUTING.md.

### CODE REVIEW

**Comment by a-developer-and-her-mac** [comment]
@RitikMody Please review.

**Comment by rubyruins** [comment]
@a-developer-and-her-mac, thanks for your interest in contributing to our repository. We are focused on welcoming absolute beginners to collaborate on the project 😊 could you please explain the procedure step by step, so that even people who are not familiar with git can contribute. Step by step instructions with syntax would be helpful.

For your reference, [here's](https://blog.scottlowe.org/2015/01/27/using-fork-branch-git-workflow/) an article that leads beginners through the entire process. Could you please make some changes to make it similar to this? Thank you!

**Comment by a-developer-and-her-mac** [comment]
I updated CONTRIBUTING.md, hopefully it looks correct this time. @rubyruins  Please review.

**Comment by rubyruins** [comment]
@a-developer-and-her-mac, looks good to me. Thank you for contributing 🎉

**Pull request merged**
